#!/bin/sh

getlocal() {
	exim -brw $1 | grep env-to: | cut -d: -f2
}

checkmatch() {
	echo -n "Check $1 -> $2 ..."
	if test $(getlocal $1) = "$2" ; then
		echo "ok"
	else
		echo "FAIL!"
		exit 1
	fi
}

checkmatch rixed-local@happyleptic.org rixed@happyleptic.org
checkmatch rixed-notlocal@happyleptic.org fail@happyleptic.org
checkmatch rixed-2048-01-21@happyleptic.org rixed@happyleptic.org
checkmatch rixed-1981-12-23@happyleptic.org fail@happyleptic.org
checkmatch rixed-local-2028-01-21@happyleptic.org rixed@happyleptic.org
checkmatch rixed-local-1981-12-23@happyleptic.org fail@happyleptic.org
checkmatch rixed-notlocal-2028-01-21@happyleptic.org fail@happyleptic.org
checkmatch rixed-notlocal-1981-12-23@happyleptic.org fail@happyleptic.org

